apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: flask-uwsgi-docker
build:
  artifacts:
  - image: darthfork/flask-uwsgi-docker
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
