apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: flask_uwsgi_docker
build:
  artifacts:
  - image: darthfork/flask_uwsgi_docker
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
