apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
  - image: flask-uwsgi-docker
deploy:
  helm:
    releases:
    - name: flask-uwsgi-docker
      chartPath: charts
      artifactOverrides:
        image: flask-uwsgi-docker
